config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    collection do
      get :search
      post :results
    end
  end

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  searchkick
  validates :title, presence: true
  validates :body, length: {maximum: 20000}
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    mapping do
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to articles_path, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
  end

  def results
    @articles = Article.search params[:search]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div data-alert class="alert-box alert radius">
      <p><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</p>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Editing article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2>Listing articles</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path, class: 'button' %>
<%= link_to 'Search Articles', search_articles_path, class: 'button secondary' %>

app/views/articles/new.html.erb
<h2>New article</h2>

<%= render 'form' %>

app/views/articles/results.html.erb
<h2>Search Results: <%= params[:search] %></h2>
<p class="right-align">Found <%= pluralize @articles.count, 'article' %></p>
<% if @articles.any? %>
  <% @articles.each do |a| %>
    <div class="result">
      <h3><%= a.title %></h3>
      <p><%= a.body %></p>
    </div>
  <% end %>
<% end %>
<%= link_to 'New Search', search_articles_path, class: 'button secondary' %>

app/views/articles/search.html.erb
<h2>Search Articles</h2>

<%= form_tag action: 'results' do %>
  <%= label_tag :search, "Keywords" %>
  <%= text_field_tag :search %>
  <%= submit_tag "Search", class: 'button' %>
  <%= link_to 'Manage Articles', articles_path, class: 'button secondary' %>
<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Demo Search Application" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div data-alert class="alert-box radius">
        <%= flash[:notice] %>
        <a href="#" class="close">&times</a>
      </div>
    <% end %>

    <div class="container">
      <h1>Demo Search Application</h1>
      <p class="subtitle">Showcasing Elasticsearch</p>
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>